export const browserCoreExamples = [
  "agent-shield browser status",
  "agent-shield browser start",
  "agent-shield browser stop",
  "agent-shield browser tabs",
  "agent-shield browser open https://example.com",
  "agent-shield browser focus abcd1234",
  "agent-shield browser close abcd1234",
  "agent-shield browser screenshot",
  "agent-shield browser screenshot --full-page",
  "agent-shield browser screenshot --ref 12",
  "agent-shield browser snapshot",
  "agent-shield browser snapshot --format aria --limit 200",
  "agent-shield browser snapshot --efficient",
  "agent-shield browser snapshot --labels",
];

export const browserActionExamples = [
  "agent-shield browser navigate https://example.com",
  "agent-shield browser resize 1280 720",
  "agent-shield browser click 12 --double",
  'agent-shield browser type 23 "hello" --submit',
  "agent-shield browser press Enter",
  "agent-shield browser hover 44",
  "agent-shield browser drag 10 11",
  "agent-shield browser select 9 OptionA OptionB",
  "agent-shield browser upload /tmp/agent-shield/uploads/file.pdf",
  'agent-shield browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "agent-shield browser dialog --accept",
  'agent-shield browser wait --text "Done"',
  "agent-shield browser evaluate --fn '(el) => el.textContent' --ref 7",
  "agent-shield browser console --level error",
  "agent-shield browser pdf",
];
